### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by talentlessguy** [deno-libs/tinyhttp#2]
- [x] App (port tests from original repo) 
- [x] Request (port tests from original repo)
- [x] Response (port tests from original repo)

**Comment by danyalasif** [comment]
I wanted to get some exposure to testing, so I tried porting over the `response` tests from the original repo @ https://github.com/deno-libs/tinyhttp/pull/10

Let me know if this is okay.

Having some issues with the chunkedEncoding part, trying to resolve that.
